const MODEL_URL='https://teachablemachine.withgoogle.com/models/wOauaqodm/';
const species=[
 {id:'chiton',aliases:['군부'],name:'군부',latin:'Acanthopleura japonica',danger:false,poison:'해당 없음',summary:'등껍질에 여덟 장의 판이 이어진 조간대 연체동물입니다. 바위에 강하게 붙어 있으므로 떼어내지 말고 관찰만 하세요.'},
 {id:'blue-ring',aliases:['파란고리문어'],name:'파란고리문어',latin:'Hapalochlaena fasciata',danger:true,poison:'테트로도톡신',summary:'자극을 받으면 파란 고리무늬가 나타날 수 있는 작은 문어입니다. 물리면 마비와 호흡 정지를 일으킬 수 있어 절대 만지면 안 됩니다.'},
 {id:'sea-hare',aliases:['군소'],name:'군소',latin:'Aplysia kurodai',danger:false,poison:'방어용 보라색 분비물',summary:'껍데기가 작아진 큰 바다민달팽이로 해조류를 먹습니다. 자극받으면 보라색 액을 낼 수 있으니 만지지 마세요.'},
 {id:'clam',aliases:['개량조개'],name:'개량조개',latin:'Mactra chinensis',danger:false,poison:'해당 없음',summary:'모래 속에 사는 두 장의 조개껍데기를 가진 조개입니다. 죽은 개체나 정체를 모르는 조개는 먹지 마세요.'},
 {id:'crab',aliases:['방게'],name:'방게',latin:'Helice tridens',danger:false,poison:'해당 없음',summary:'갯벌과 바위틈에서 볼 수 있는 작은 게입니다. 집게에 물릴 수 있으므로 잡거나 자극하지 마세요.'},
 {id:'barnacle',aliases:['따개비'],name:'따개비',latin:'Balanomorpha',danger:false,poison:'해당 없음',summary:'바위·부표 등에 단단히 붙어 사는 갑각류입니다. 껍질 가장자리가 날카로울 수 있어 맨손 접촉을 피하세요.'},
 {id:'purple-urchin',aliases:['보라성게'],name:'보라성게',latin:'Anthocidaris crassispina',danger:false,poison:'가시 자극성 물질',summary:'보라색의 긴 가시를 가진 성게입니다. 가시에 찔리면 통증과 염증이 생길 수 있으니 밟거나 만지지 마세요.'},
 {id:'sea-urchin',aliases:['말똥성게'],name:'말똥성게',latin:'Mesocentrotus nudus',danger:false,poison:'가시 자극성 물질',summary:'검고 짧은 가시가 빽빽한 성게입니다. 가시에 찔릴 위험이 있으므로 신발을 신고 거리를 두세요.'},
 {id:'hermit',aliases:['소라게'],name:'소라게',latin:'Paguroidea',danger:false,poison:'해당 없음',summary:'다른 생물의 빈 껍데기를 집으로 사용하는 갑각류입니다. 약한 개체가 껍데기에서 나오지 않도록 관찰만 하세요.'},
 {id:'starfish',aliases:['별불가살','별불가사리'],name:'별불가사리',latin:'Asterina pectinifera',danger:false,poison:'해당 없음',summary:'별 모양의 팔을 가진 불가사리입니다. 사람에게 독성은 알려져 있지 않지만 야생 생물은 만지지 마세요.'},
 {id:'amur',aliases:['아무르불가사리'],name:'아무르불가사리',latin:'Asterias amurensis',danger:false,poison:'해당 없음',summary:'다섯 개의 팔을 가진 불가사리로 연안에서 관찰됩니다. 생태계에 영향을 줄 수 있어 임의로 옮기지 마세요.'},
 {id:'brittle',aliases:['거미불가사리'],name:'거미불가사리',latin:'Ophiuroidea',danger:false,poison:'해당 없음',summary:'가늘고 긴 팔로 빠르게 움직이는 극피동물입니다. 팔이 쉽게 끊어질 수 있으므로 손대지 마세요.'},
 {id:'moon',aliases:['보름달물해파리'],name:'보름달물해파리',latin:'Aurelia aurita',danger:false,poison:'약한 자포 독액',summary:'몸속에 네 개의 둥근 생식소가 보이는 해파리입니다. 약한 자극도 생길 수 있으므로 죽어 있어도 만지지 마세요.'},
 {id:'nomura',aliases:['노무라입깃해파리'],name:'노무라입깃해파리',latin:'Nemopilema nomurai',danger:false,poison:'자포 독액',summary:'크게 자라는 해파리로 촉수에 닿으면 통증과 피부 자극이 생길 수 있습니다. 접촉했다면 바닷물로 씻고 통증이 심하면 진료를 받으세요.'},
 {id:'siphonophore',aliases:['작은부레관해파리'],name:'작은부레관해파리',latin:'Physalia physalis',danger:false,poison:'자포 독액',summary:'부레처럼 떠다니며 긴 촉수를 가진 군체성 자포동물입니다. 촉수의 자포 독액이 강할 수 있으니 절대 만지지 마세요.'},
 {id:'anemone',aliases:['말미잘'],name:'말미잘',latin:'Actiniaria',danger:false,poison:'자포 독액',summary:'바위에 붙어 촉수를 펼치는 자포동물입니다. 촉수에 약한 자극성 독액이 있으므로 관찰만 하세요.'},
 {id:'octopus',aliases:['문어'],name:'문어',latin:'Octopus vulgaris',danger:false,poison:'해당 없음',summary:'여덟 개의 팔을 가진 두족류입니다. 해변에 떠밀려 온 개체는 약해져 있을 수 있으니 직접 만지지 마세요.'}
];
const $=q=>document.querySelector(q),guideKey='shorewatch-guide',hazardKey='shorewatch-hazards',hazardInitKey='shorewatch-hazard-initialized-v2';let model,current;
const entries=()=>JSON.parse(localStorage.getItem(guideKey)||'[]');
function fromLabel(label){const value=label.toLowerCase().replaceAll(' ','');return species.find(s=>s.aliases.some(a=>value.includes(a.replaceAll(' ',''))))||{id:'unknown',name:'알 수 없는 클래스',latin:'확인 필요',danger:false,poison:'확인 필요',summary:'현재 모델의 17개 학습 클래스와 이름을 연결하지 못했습니다. 생물에 접근하거나 만지지 마세요.'}}
async function loadModel(){if(model)return model;$('#modelStatus').textContent='Teachable Machine 모델을 불러오는 중입니다…';try{model=await tmImage.load(MODEL_URL+'model.json',MODEL_URL+'metadata.json');$('#modelStatus').textContent='AI 모델 준비 완료 · 사진을 올려 분석하세요.';return model}catch(e){$('#modelStatus').textContent='모델을 불러오지 못했습니다. 인터넷 연결을 확인해 주세요.';throw e}}
function renderGuide(){const d=entries();$('#guideList').innerHTML=d.length?d.map(e=>`<article class="entry"><img class="entry-image" data-id="${e.id}" src="${e.image}" alt="${e.name}"><div class="entry-body"><h3>${e.name}</h3><p>${e.beach} · ${e.date}</p><p>${e.danger?'⚠ 위험 생물':'✓ 일반 관찰'}</p><button class="delete" data-id="${e.id}">도감에서 삭제</button></div></article>`).join(''):'<p class="empty">아직 저장한 생물이 없어요.</p>';document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{localStorage.setItem(guideKey,JSON.stringify(d.filter(x=>x.id!==b.dataset.id)));renderGuide()});document.querySelectorAll('.entry-image').forEach(i=>i.onclick=()=>openEntry(d.find(x=>x.id===i.dataset.id)))}
function renderMap(){const h=JSON.parse(localStorage.getItem(hazardKey)||'[]');$('#beachMap').innerHTML=['해운대','광안리','송도','다대포'].map(b=>{const items=h.filter(x=>x.beach===b),reports=items.map(x=>`<button class="remove-hazard" data-id="${x.id}">위험 표시 제거</button>`).join('');return `<article class="beach"><h3>${b} 해수욕장</h3><p>공유 위험 제보</p><span class="pin" style="background:${items.length?'#e6604f':'#4a9b85'}">${items.length?'⚠ 위험 표시 '+items.length+'건':'✓ 현재 제보 없음'}</span>${reports}</article>`}).join('');document.querySelectorAll('.remove-hazard').forEach(b=>b.onclick=()=>{localStorage.setItem(hazardKey,JSON.stringify(h.filter(x=>x.id!==b.dataset.id)));renderMap()})}
$('#photoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('#preview').src=r.result;$('#preview').style.display='block';$('#uploadIcon').style.display='none'};r.readAsDataURL(f)};
$('#analyzeButton').onclick=async()=>{const image=$('#preview');if(!image.src)return alert('먼저 생물 사진을 올려주세요.');const button=$('#analyzeButton');button.disabled=true;button.textContent='Teachable Machine이 비교 분석 중입니다…';$('#modelStatus').textContent='17개 학습 클래스와 사진을 비교하고 있습니다.';try{const ai=await loadModel(),all=(await ai.predict(image)).sort((a,b)=>b.probability-a.probability),chosen=all[0];current={...fromLabel(chosen.className),confidence:Math.round(chosen.probability*100),modelLabel:chosen.className,rankings:all.slice(0,3)};$('#modelStatus').textContent='비교 분석을 완료했습니다.';showResult()}catch(e){$('#modelStatus').textContent='분석을 시작하지 못했습니다.';alert('AI 모델을 불러오지 못했습니다. 인터넷 연결 후 다시 시도해 주세요.')}finally{button.disabled=false;button.textContent='AI로 생물 분석하기'}};
function showResult(){const s=current,rankings=s.rankings.map((x,i)=>`<small>${i+1}위 · ${fromLabel(x.className).name} ${Math.round(x.probability*100)}%</small>`).join('<br>');$('#result').innerHTML=`<div class="result-head"><div><p class="eyebrow">TEACHABLE MACHINE 비교 분석 · 1위 유사도 ${s.confidence}%</p><h3>${s.name}</h3><p class="latin">${s.latin}</p><p class="hint">${rankings}</p></div><span class="risk ${s.danger?'danger':'safe'}">${s.danger?'⚠ 유해 생물':'✓ 유해 정보 없음'}</span></div><div class="result-detail"><div><b>도감 요약</b><br>${s.summary}</div><div><b>독성 정보</b><br>${s.danger?`독의 종류: ${s.poison}`:'독성 정보 없음'}</div></div>${s.danger?'<div class="report-action"><b>신고 권고</b> · 생물에 접근하지 말고 주변에 알린 뒤, 긴급하면 119 또는 112로 신고하세요. 해양 사고는 122에도 신고할 수 있습니다.</div>':''}<button id="saveGuide" class="button">내 도감에 저장</button>${s.danger?'<button id="reportHazard" class="outline" style="margin-left:8px">공유 지도에 위험 표시</button>':''}`;$('#result').classList.remove('hidden');$('#saveGuide').onclick=save;const b=$('#reportHazard');if(b)b.onclick=report}
function save(){let d=entries();d.unshift({id:crypto.randomUUID(),speciesId:current.id,name:current.name,beach:$('#beach').value,date:new Date().toLocaleDateString('ko-KR'),danger:current.danger,image:$('#preview').src,summary:current.summary,poison:current.poison,latin:current.latin});localStorage.setItem(guideKey,JSON.stringify(d));renderGuide();alert('도감에 저장했습니다. 다음에 다시 와도 이 기기에서 볼 수 있어요.')}
function report(){let h=JSON.parse(localStorage.getItem(hazardKey)||'[]');h.unshift({id:crypto.randomUUID(),beach:$('#beach').value,species:current.name,date:Date.now()});localStorage.setItem(hazardKey,JSON.stringify(h));renderMap();location.hash='map';alert('공유 지도에 위험 표시를 추가했습니다. 실제 긴급 신고는 119 또는 122를 이용하세요.')}
function openEntry(e){const s={...e,summary:e.summary||'저장된 생물 정보입니다.',poison:e.poison||'확인 필요'};$('#entryDialog').innerHTML=`<form method="dialog"><button class="close">×</button><h2>${s.name}</h2><img style="width:100%;max-height:230px;object-fit:cover" src="${s.image}" alt="${s.name}"><p><i>${s.latin||''}</i></p><div class="result-detail"><div><b>도감 요약</b><br>${s.summary}</div><div><b>독성 정보</b><br>${s.danger?`독의 종류: ${s.poison}`:'독성 정보 없음'}</div></div>${s.danger?'<p class="report-action">⚠ 유해 생물입니다. 긴급 시 119 또는 112에 연락하세요. 해양 사고는 122에도 신고할 수 있습니다.</p>':''}</form>`;$('#entryDialog').showModal()}
if(!localStorage.getItem(hazardInitKey)){localStorage.setItem(hazardKey,'[]');localStorage.setItem(hazardInitKey,'true')}loadModel();renderGuide();renderMap();
