const MODEL='https://teachablemachine.withgoogle.com/models/wOauaqodm/';
const BEACH={해운대:[35.1587,129.1604],광안리:[35.1532,129.1186],송도:[35.0767,129.0168],다대포:[35.0485,128.9677]};
const SPECIES={군부:['군부',false,'해당 없음','갯바위에 붙어 사는 조개류입니다. 관찰만 하고 떼어내지 마세요.'],파란고리문어:['파란고리문어',true,'테트로도톡신','푸른 고리무늬가 특징입니다. 강한 신경독이 있어 절대 만지지 마세요.'],군소:['군소',false,'약한 방어 분비물','부드러운 몸을 가진 해양 복족류입니다. 해변 생물은 만지지 않는 것이 좋습니다.'],개량조개:['개량조개',false,'해당 없음','모래에 사는 조개입니다. 살아 있는 개체는 제자리에 두세요.'],방게:['방게',false,'해당 없음','바위틈에 사는 작은 게입니다. 집게에 물릴 수 있어 관찰만 하세요.'],따개비:['따개비',false,'해당 없음','바위나 구조물에 붙어 사는 갑각류입니다. 날카로운 껍질에 주의하세요.'],보라성게:['보라성게',false,'가시 자극','보라색 가시가 있는 성게입니다. 가시에 찔리지 않도록 만지지 마세요.'],말똥성게:['말똥성게',false,'가시 자극','둥근 성게입니다. 가시는 상처를 만들 수 있습니다.'],소라게:['소라게',false,'해당 없음','빈 조개껍데기를 집으로 쓰는 갑각류입니다. 껍데기를 빼앗지 마세요.'],별불가사리:['별불가사리',false,'해당 없음','별 모양의 극피동물입니다. 야생 생물은 손대지 말고 관찰하세요.'],아무르불가사리:['아무르불가사리',false,'해당 없음','다섯 팔을 가진 불가사리입니다. 임의로 옮기지 마세요.'],거미불가사리:['거미불가사리',false,'해당 없음','가느다란 팔로 움직이는 극피동물입니다. 팔이 쉽게 손상됩니다.'],보름달물해파리:['보름달물해파리',false,'약한 자포 독액','약한 독성이지만 죽어 있어도 쏠 수 있습니다. 접근과 접촉을 보류하세요.','주의종'],노무라입깃해파리:['노무라입깃해파리',true,'자포 독액','큰 해파리로 촉수 접촉 시 통증과 피부 자극이 생길 수 있습니다.'],작은부레관해파리:['작은부레관해파리',true,'강한 자포 독액','부레와 긴 촉수를 가진 군체성 자포동물입니다. 매우 위험하니 접근하지 마세요.'],말미잘:['말미잘',false,'자포 독액','바위에 붙어 촉수를 펼치는 자포동물입니다. 만지지 말고 관찰하세요.'],문어:['문어',false,'해당 없음','여덟 팔을 가진 두족류입니다. 떠밀려 온 개체도 손대지 마세요.']};
let model,current,gps=null,user=null,guides=[],hazards=[],guideStop,hazardStop;
const decoration=document.createElement('div');decoration.className='monster-ball';decoration.setAttribute('aria-hidden','true');document.body.append(decoration);
const decorationStyle=document.createElement('style');decorationStyle.textContent='.monster-ball{position:fixed;right:22px;bottom:22px;width:62px;height:62px;border-radius:50%;z-index:7;background:linear-gradient(#ee4d4d 0 47%,#1b2731 48% 53%,#fff 54%);box-shadow:0 8px 18px #062b4866;border:3px solid #1b2731}.monster-ball:after{content:"";position:absolute;top:50%;left:50%;width:19px;height:19px;transform:translate(-50%,-50%);border-radius:50%;background:#fff;border:5px solid #1b2731;box-shadow:0 0 0 2px #fff}.monster-ball:hover{transform:rotate(18deg) scale(1.08)}';document.head.append(decorationStyle);
const $=s=>document.querySelector(s);const guest=()=>sessionStorage;
function normalized(label){return Object.keys(SPECIES).find(k=>label.includes(k))||'문어'}
async function load(){if(!model)model=await tmImage.load(MODEL+'model.json',MODEL+'metadata.json');return model}
function map(beach){const [lat,lng]=BEACH[beach];$('#googleMap').innerHTML=`<iframe title="${beach} 지도" src="https://www.google.com/maps?q=${lat},${lng}&z=15&output=embed"></iframe>`}
function renderMap(){ $('#hazardCount').textContent=`위험 표시 ${hazards.length}건`;$('#mapHazards').innerHTML=hazards.length?hazards.map(x=>`<div class="hazard"><span>⚠ ${x.beach} · ${x.species}<br><small>${x.lat.toFixed(5)}, ${x.lng.toFixed(5)}</small></span>${user&&x.reporterId===user.uid?`<button class="remove" data-id="${x.id}">삭제하기</button>`:''}</div>`).join(''):'<p>현재 위험 표시는 0건입니다.</p>';document.querySelectorAll('.remove').forEach(b=>b.onclick=()=>window.firebaseService.deleteHazard(b.dataset.id));}
function renderGuide(){ $('#guideList').innerHTML=guides.length?guides.map(x=>`<article class="entry"><img data-id="${x.id}" src="${x.image}" alt="${x.name}"><div><h3>${x.name}</h3><p>${x.beach} · ${x.date}</p><p>${x.lat.toFixed(5)}, ${x.lng.toFixed(5)}</p><button class="remove" data-id="${x.id}">도감에서 삭제</button></div></article>`).join(''):'<p>아직 저장한 생물이 없어요.</p>';document.querySelectorAll('.entry img').forEach(i=>i.onclick=()=>openEntry(guides.find(x=>x.id===i.dataset.id)));document.querySelectorAll('#guideList .remove').forEach(b=>b.onclick=()=>user?window.firebaseService.deleteGuide(user.uid,guides.find(x=>x.id===b.dataset.id)):(guides=guides.filter(x=>x.id!==b.dataset.id),guest().setItem('aqua-guest-guides',JSON.stringify(guides)),renderGuide()));}
function openEntry(x){$('#entryDialog').innerHTML=`<form method="dialog"><button class="remove">× 닫기</button><h2>${x.name}</h2><img src="${x.image}"><p><b>도감 요약</b><br>${x.summary}</p><p><b>독성 정보</b><br>${x.poison}</p><p>${x.beach} · ${x.date}<br>${x.lat.toFixed(5)}, ${x.lng.toFixed(5)}</p></form>`;$('#entryDialog').showModal()}
function setup(){const s=window.firebaseService;if(!s?.ready)return;s.onUser(u=>{user=u;$('#authStatus').textContent=u?(u.displayName||'로그인됨'):'비회원';$('#loginButton').textContent=u?'로그아웃':'Google 로그인';if(guideStop)guideStop();if(hazardStop)hazardStop();if(u){guideStop=s.listenGuides(u.uid,d=>{guides=d;renderGuide()});hazardStop=s.listenHazards(d=>{hazards=d;renderMap()})}else{guides=JSON.parse(guest().getItem('aqua-guest-guides')||'[]');hazards=[];renderGuide();renderMap()}})}
$('#photoInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('#preview').src=r.result;$('#preview').style.display='block';$('#uploadIcon').style.display='none'};r.readAsDataURL(f);try{const p=await exifr.gps(f);gps=p?{lat:p.latitude,lng:p.longitude}:null}catch{gps=null}$('#gpsStatus').textContent=gps?`사진 GPS: ${gps.lat.toFixed(6)}, ${gps.lng.toFixed(6)}`:'사진 GPS가 없습니다. 선택한 해수욕장 중심 좌표로 저장됩니다.'};
$('#analyzeButton').onclick=async()=>{if(!$('#preview').src)return alert('먼저 생물 사진을 올려주세요.');try{const p=(await (await load()).predict($('#preview'))).sort((a,b)=>b.probability-a.probability);const n=normalized(p[0].className),d=SPECIES[n];current={name:n,danger:d[1],poison:d[2],summary:d[3],kind:d[4]||'',ranking:p.slice(0,3)};const ranks=current.ranking.map((x,i)=>`${i+1}위 ${normalized(x.className)} ${Math.round(x.probability*100)}%`).join(' · ');$('#result').innerHTML=`<div class="result-head"><div><p class="eyebrow">ANALYSIS RESULT</p><h3>${n}</h3><small>${ranks}</small></div><span class="risk ${current.danger?'danger':current.kind?'caution':'safe'}">${current.danger?'위험종':current.kind||'유해 정보 없음'}</span></div><div class="result-detail"><div><b>도감 요약</b><br>${d[3]}</div><div><b>독성 정보</b><br>${d[2]}</div></div>${current.danger?'<p class="report-action">⚠ 위험종입니다. 접근하지 말고 119 또는 해양경찰 122 신고를 고려하세요.</p>':current.kind?'<p class="report-action">△ 주의종입니다. 약한 독성도 있으므로 접근을 보류하세요.</p>':''}<button id="save" class="primary">내 도감에 저장</button>${current.danger?'<button id="report" class="remove">공유 지도에 위험 표시</button>':''}`;$('#result').classList.remove('hidden');$('#save').onclick=save;const r=$('#report');if(r)r.onclick=report}catch(e){alert('분석 모델을 불러오지 못했습니다. 인터넷 연결을 확인하세요.')}};
function entry(){const p=gps||{lat:BEACH[$('#beach').value][0],lng:BEACH[$('#beach').value][1]};return{id:crypto.randomUUID(),name:current.name,beach:$('#beach').value,date:new Date().toLocaleDateString('ko-KR'),image:$('#preview').src,summary:current.summary,poison:current.poison,lat:p.lat,lng:p.lng}}
async function save(){const x=entry();if(user)await window.firebaseService.saveGuide(user.uid,x);else{guides.unshift(x);guest().setItem('aqua-guest-guides',JSON.stringify(guides));renderGuide()}alert('도감에 저장했습니다.')}
async function report(){const x={...entry(),species:current.name,reporterId:user?.uid||null};if(!user)return alert('공유 위험 표시는 Google 로그인 후 이용할 수 있습니다.');await window.firebaseService.saveHazard(x);location.hash='map'}
$('#loginButton').onclick=async()=>{try{user?await window.firebaseService.logout():await window.firebaseService.login()}catch(e){alert('로그인에 실패했습니다: '+(e.code||e.message))}};document.querySelectorAll('[data-beach]').forEach(b=>b.onclick=()=>map(b.dataset.beach));map('해운대');setup();window.addEventListener('firebase-service-ready',setup);load().then(()=>$('#modelStatus').textContent='17종 비교 분석 모델이 준비되었습니다.');
