const BEACHES={해운대:{lat:35.1587,lng:129.1604,zoom:15},광안리:{lat:35.1532,lng:129.1186,zoom:15},송도:{lat:35.0767,lng:129.0168,zoom:15},다대포:{lat:35.0485,lng:128.9677,zoom:14}};
let currentGPS=null,mapInstance=null,appUser=null,guideEntries=[],hazardEntries=[],guideUnsub=null,hazardUnsub=null;
const guestStore=()=>sessionStorage;
function placeMap(beach){const p=BEACHES[beach];if(mapInstance){mapInstance.setCenter(p);mapInstance.setZoom(p.zoom);return}document.querySelector('#googleMap').innerHTML=`<iframe class="google-map" title="${beach} 지도" src="https://www.google.com/maps?q=${p.lat},${p.lng}&z=${p.zoom}&output=embed"></iframe>`}
function initRestrictedGoogleMap(){const key=window.APP_CONFIG?.googleMapsApiKey;if(!key){placeMap('해운대');return}window.__shoreMapReady=()=>{const bounds={north:35.18,south:35.03,east:129.18,west:128.94};mapInstance=new google.maps.Map(document.querySelector('#googleMap'),{center:BEACHES.해운대,zoom:13,minZoom:12,maxZoom:18,restriction:{latLngBounds:bounds,strictBounds:true},zoomControl:true,streetViewControl:false,mapTypeControl:false});renderMap()};const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${key}&callback=__shoreMapReady`;script.async=true;document.head.append(script)}
function displayLocation(){document.querySelector('#gpsStatus').textContent=currentGPS?`사진 GPS: ${currentGPS.lat.toFixed(6)}, ${currentGPS.lng.toFixed(6)}`:'사진에 GPS가 없습니다. 선택한 해수욕장 중심 좌표로 저장됩니다.'}
document.querySelector('#photoInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{document.querySelector('#preview').src=reader.result;document.querySelector('#preview').style.display='block';document.querySelector('#uploadIcon').style.display='none'};reader.readAsDataURL(file);try{const gps=await exifr.gps(file);currentGPS=gps?{lat:gps.latitude,lng:gps.longitude}:null}catch{currentGPS=null}displayLocation()};
document.querySelectorAll('[data-beach]').forEach(b=>b.onclick=()=>placeMap(b.dataset.beach));
function syncAuthUI(){document.querySelector('#authStatus').textContent=appUser?`${appUser.displayName||appUser.email}님`:'비회원';document.querySelector('#loginButton').textContent=appUser?'로그아웃':'Google 로그인';document.querySelector('#guideStatus').textContent=appUser?'Firebase에 저장됨 · 다른 기기에서도 동기화':'비회원 저장은 앱 종료 후 사라집니다'}
function setupFirebase(){const service=window.firebaseService;if(!service?.ready){syncAuthUI();return}service.onUser(user=>{appUser=user;syncAuthUI();if(guideUnsub)guideUnsub();if(hazardUnsub)hazardUnsub();if(user){guideUnsub=service.listenGuides(user.uid,data=>{guideEntries=data;renderGuide()});hazardUnsub=service.listenHazards(data=>{hazardEntries=data;renderMap()})}else{guideEntries=JSON.parse(guestStore().getItem(guideKey)||'[]');hazardEntries=JSON.parse(localStorage.getItem(hazardKey)||'[]');renderGuide();renderMap()}})}
window.addEventListener('firebase-service-ready',setupFirebase);setTimeout(setupFirebase,0);
document.querySelector('#loginButton').onclick=async()=>{const service=window.firebaseService;if(!service?.ready)return alert('Firebase 설정이 아직 없습니다. config.js에 Firebase 웹 설정을 넣은 뒤 Google 로그인을 활성화하세요.');try{appUser?await service.logout():await service.login()}catch(e){alert(`로그인에 실패했습니다: ${e.code||e.message}`)}};
function renderMap(){const reports=hazardEntries;document.querySelector('#mapHazards').innerHTML=reports.length?reports.map(r=>`<div class="map-hazard"><span>⚠ ${r.beach} · ${r.species}${r.lat?` · ${r.lat.toFixed(4)}, ${r.lng.toFixed(4)}`:''}</span>${appUser?`<button class="remove-hazard" data-id="${r.id}">삭제하기</button>`:''}</div>`).join(''):'<p class="empty">현재 위험 표시는 0건입니다.</p>';document.querySelectorAll('.remove-hazard').forEach(b=>b.onclick=async()=>{if(appUser)await window.firebaseService.deleteHazard(b.dataset.id);else{hazardEntries=reports.filter(x=>x.id!==b.dataset.id);localStorage.setItem(hazardKey,JSON.stringify(hazardEntries));renderMap()}})}
function newEntry(){const s=current,p=currentGPS||BEACHES[document.querySelector('#beach').value];return{id:crypto.randomUUID(),speciesId:s.id,name:s.name,beach:document.querySelector('#beach').value,date:new Date().toLocaleDateString('ko-KR'),danger:s.danger,image:document.querySelector('#preview').src,summary:s.summary,poison:s.poison,latin:s.latin,lat:p.lat,lng:p.lng}}
async function save(){const entry=newEntry();if(appUser){try{await window.firebaseService.saveGuide(appUser.uid,entry);alert('Google 계정 도감에 저장했습니다. 다른 기기에서도 로그인하면 볼 수 있어요.')}catch(e){alert(`저장에 실패했습니다: ${e.code||e.message}`)}}else{guideEntries.unshift(entry);guestStore().setItem(guideKey,JSON.stringify(guideEntries));renderGuide();alert('비회원 도감에 임시 저장했습니다. 앱을 종료하면 사라집니다.')}}
async function report(){const p=currentGPS||BEACHES[document.querySelector('#beach').value],entry={id:crypto.randomUUID(),beach:document.querySelector('#beach').value,species:current.name,date:Date.now(),lat:p.lat,lng:p.lng,reporterId:appUser?.uid||null};if(appUser)await window.firebaseService.saveHazard(entry);else{hazardEntries.unshift(entry);localStorage.setItem(hazardKey,JSON.stringify(hazardEntries));renderMap()}location.hash='map';alert('위험 표시를 추가했습니다. 실제 긴급 신고는 119 또는 122를 이용하세요.')}
function renderGuide(){const data=guideEntries;document.querySelector('#guideList').innerHTML=data.length?data.map(e=>`<article class="entry"><img class="entry-image" data-id="${e.id}" src="${e.imageUrl||e.image}" alt="${e.name}"><div class="entry-body"><h3>${e.name}</h3><p>${e.beach} · ${e.date}</p><p>${Number(e.lat).toFixed(5)}, ${Number(e.lng).toFixed(5)}</p><button class="delete" data-id="${e.id}">도감에서 삭제</button></div></article>`).join(''):'<p class="empty">아직 저장한 생물이 없어요.</p>';document.querySelectorAll('.delete').forEach(b=>b.onclick=async()=>{const entry=data.find(x=>x.id===b.dataset.id);if(appUser)await window.firebaseService.deleteGuide(appUser.uid,entry);else{guideEntries=data.filter(x=>x.id!==b.dataset.id);guestStore().setItem(guideKey,JSON.stringify(guideEntries));renderGuide()}});document.querySelectorAll('.entry-image').forEach(i=>i.onclick=()=>openEntry(data.find(x=>x.id===i.dataset.id)))}
initRestrictedGoogleMap();guideEntries=JSON.parse(guestStore().getItem(guideKey)||'[]');hazardEntries=JSON.parse(localStorage.getItem(hazardKey)||'[]');renderMap();renderGuide();displayLocation();
